import {Dimensions, Image, Text, TouchableOpacity, View} from 'react-native';
import COLORS from '../../constants/Colors';
import {useNavigation} from '@react-navigation/native';
import axios from 'axios';
import {useEffect, useState} from 'react';
const height = Dimensions.get('window').height;
export default function TournamentEventCards({data}) {
  const navigation = useNavigation();
  const [multidata, setMultiData] = useState([]);
  const getMultSportsData = async () => {
    try {
      let res = await axios({
        method: 'get',
        url: 'http://15.206.246.81:3000/tournaments/filter/data?userId=661128d8ee8b461b00d95edd&page=0&limit=20',
      });
      setMultiData(res.data.data);
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    getMultSportsData();
  }, []);

  return (
    <View
      style={{
        backgroundColor: COLORS.white,
        padding: 16,
        height: height - 200,
        flexDirection: 'row',
        gap: 16,
        flexWrap: 'wrap',
        justifyContent:
          (data || multidata)?.length > 2 ? 'space-evenly' : 'flex-start',
      }}>
      {(data || multidata)?.map((item, index) => {
        return (
          <TouchableOpacity
            key={index}
            style={{
              borderWidth: 1,
              borderColor: COLORS.light_gray,
              width: 100,
              height: 100,
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
              borderRadius: 10,
              backgroundColor: COLORS.white,
            }}
            onPress={() => {
              navigation.navigate('tournament-view', {
                tournamentDetail: item,
              });
            }}>
            <Image
              source={
                item?.coverImage
                  ? {uri: item?.coverImage}
                  : require('../../assets/images/olympic.png')
              }
              style={{
                width: 80,
                height: 50,
                objectFit: 'contain',
                borderRadius: 10,
              }}
            />
            <Text style={{color: COLORS.black}}>{item?.name}</Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
}

// const r = {
//   __v: 0,
//   _id: '66424ecd5e05d1ce01df4f40',
//   coverImage:
//     'https://st3.depositphotos.com/3591429/18305/i/380/depositphotos_183057156-stock-photo-sports-tools-green-grass-concept.jpg',
//   createdAt: '2024-05-13T17:33:01.583Z',
//   domesticAndInternational: 'International',
//   edition: '2024-2025',
//   endDate: '2024-05-14T00:00:00.000Z',
//   icon: 'https://sunday-venture.s3.ap-south-1.amazonaws.com/tournament/custom-erp-software-development.gif',
//   isActive: true,
//   isDeleted: false,
//   isFavorite: false,
//   location: 'fake',
//   name: 'Archery Team',
//   sport: 'ARCHERY',
//   sportType: 'Individual Sporting',
//   sports: [],
//   standing: [
//     {
//       _id: '664c4bdb4fc59d4570a9bb1a',
//       country: 'Albania',
//       player: [Object],
//       rank: '0',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb1b',
//       country: 'Croatia',
//       player: [Object],
//       rank: '1',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb1c',
//       country: 'Albania',
//       player: [Object],
//       rank: '2',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb1d',
//       country: 'Sudan',
//       player: [Object],
//       rank: '3',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb1e',
//       country: 'Turkmenistan',
//       player: [Object],
//       rank: '4',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb1f',
//       country: 'India',
//       player: [Object],
//       rank: '5',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb20',
//       country: 'India',
//       player: [Object],
//       rank: '6',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb21',
//       country: 'Venezuela',
//       player: [Object],
//       rank: '7',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb22',
//       country: 'Turkmenistan',
//       player: [Object],
//       rank: '8',
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb23',
//       country: 'Croatia',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb24',
//       country: 'Zambia',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb25',
//       country: 'Somalia',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb26',
//       country: 'India',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb27',
//       country: 'India',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb28',
//       country: 'India',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb29',
//       country: 'Cook Islands',
//       player: [Object],
//       result: null,
//     },
//     {
//       _id: '664c4bdb4fc59d4570a9bb2a',
//       country: 'India',
//       player: [Object],
//       result: null,
//     },
//   ],
//   startDate: '2024-05-13T00:00:00.000Z',
//   subTournaments: [],
//   tags: ['hello', 'world'],
//   updatedAt: '2024-05-21T07:23:07.469Z',
// };

// let e = {
//   Gender: ['Male', 'Female', 'Other'],
//   ParticipationType: ['A Vs B', 'Group'],
//   RecordLevel: ['Indian', 'Asian', 'World', 'Olympics'],
//   SportingType: ['Individual Sporting', 'Multi-Sporting'],
//   TournamentType: ['International', 'Domestic'],
//   eventCategory: {
//     ARCHERY: [
//       'Recurve Individual',
//       'Recurve Team',
//       'Recurve Mixed Team',
//       'Compound Individual',
//       'Compound Team',
//       'Compound Mixed Team',
//     ],
//     ATHLETICS: [
//       '60m',
//       '100m',
//       '200m',
//       '400m',
//       '800m',
//       '1500m',
//       '3000m',
//       '5000m',
//       '10000m',
//       '60m Hurdles',
//       '100m Hurdles',
//       '110m Hurdles',
//       '3000m Steeplechase',
//       '4x100m Relay',
//       '4x400m Relay',
//       '1 Mile',
//       '4x400m Mixed Relay',
//       'Long Jump',
//       'Triple Jump',
//       'High Jump',
//       'Pole Vault',
//       'Shot Put',
//       'Discus Throw',
//       'Hammer Throw',
//       'Javelin Throw',
//       'Pentathlon',
//       'Heptathlon',
//       'Decathlon',
//       'Full Marathon',
//       'Half Marathon',
//       '10km Marathon',
//       '5km Marathon',
//       '10km Race Walkin',
//       '20km Race Walking',
//       '35km Race Walking',
//       '50km Race Walking',
//       '10000m Race Walking',
//       '20000m Race Walking',
//       'Cross Country',
//     ],
//     BADMINTON: ['Singles', 'Doubles', 'Mixed Doubles', 'Team Event'],
//     BASKETBALL: ['Basketball', '3x3 Basketball'],
//     BOXING: [
//       "45kg to 48kg - Women's Minimumweight",
//       "46kg to 48kg - Men's Minimumweight",
//       "50kg - Women's Light Flyweight",
//       "51kg - Men's Flyweight",
//       "52kg - Women's Flyweight",
//       "54kg - Women's Bantamweight",
//       "54kg - Men's Bantamweight",
//       "57kg - Men's Featherweight",
//       "57kg - Women's Featherweight",
//       "60kg - Men's Lightweight",
//       "60kg - Women's Lightweight",
//       "63kg - Women's Light Welterweight",
//       "63.5kg - Men's Light Welterweight",
//       "66kg - Women's Welterweight",
//       "67kg - Men's Welterweight",
//       "70kg - Women's Light Middleweight",
//       "71kg - Men's Light Middleweight",
//       "75kg - Men's Middleweight",
//       "75kg - Women's Middleweight",
//       "80kg - Men's Light Heavyweight",
//       "81kg - Women's Light Heavyweight",
//       "81kg+ - Women's Heavyweight",
//       "86kg - Men's Cruiserweight",
//       "92kg - Men's Heavyweight",
//       "92kg+ - Men's Super Heavyweight",
//     ],
//     CANOEING: [
//       'Canoe Slalom: C-1',
//       'Canoe Slalom: K-1',
//       'Canoe Slalom: KX-1',
//       'Canoe Sprint: C-1 200m',
//       'Canoe Sprint: C-1 1000m',
//       'Canoe Sprint: C-2 500m',
//       'Canoe Sprint: K-1 500m',
//       'Canoe Sprint: K-1 1000m',
//       'Canoe Sprint: K-2 500m',
//       'Canoe Sprint: K-4 500m',
//       'Rowing Sweep: Coxless Pair',
//       'Rowing Sweep: Coxless Four',
//       'Rowing Sweep: Coxless Eight',
//       'Rowing Sculling: Single Sculls',
//       'Rowing Sculling: Double Sculls',
//       'Rowing Sculling: Quadraple Sculls',
//       'Rowing Lightweight Sculling: Double Sculls',
//     ],
//     CYCLING: [
//       'Road Individual Time Trials',
//       'Road racing',
//       'Track - Indvidual Sprint',
//       'Track - Keirin',
//       'Track - Team Sprint',
//       'Track - Tram Pursuit',
//       'Track - Madison',
//       'Track - Omnium',
//       'Mountain Biking - Cross Country',
//       'BMX Racing',
//       'BMX Freestyle',
//       'Cyclocross',
//     ],
//     EQUESTRIAN: [
//       'Individual Dressage',
//       'Team Dressage',
//       'Individual Jumping',
//       'Team Jumping',
//       'Individual Eventing',
//       'Team Eventing',
//     ],
//     FENCING: ['FOIL', 'Team FOIL', 'EPEE', 'Team EPEE', 'SABRE', 'Team SABRE'],
//     FOOTBALL: ['FOOTBALL'],
//     GOLF: ['Golf', 'Team Golf'],
//     GYMNASTICS: [
//       'ARTISTIC Team All Around',
//       "ARTISTIC Men's Individual All Around",
//       "ARTISTIC Women's Individual All Around",
//       'ARTISITIC Individual',
//       "RHYTHMIC Women's Team All Around",
//       "RHYTHMIC Women's Individual All Around",
//       'TRAMPOLINE',
//     ],
//     HANDBALL: ['HANDBALL'],
//     HOCKEY: ['HOCKEY'],
//     JUDO: [
//       "48kg - Women's Extra Lightweight",
//       "52kg - Women's Half Lightweight",
//       "57kg - Women's Half Lightweight",
//       "60kg - Men's Extra Lightweight",
//       "63kg - Women's Half Middleweight",
//       "66kg - Men's Half Lightweight",
//       "70kg - Women's Middleweight",
//       "73kg - Men's Lightweight",
//       "78kg - Women's Half Heavyweight",
//       "78kg+ - Women's Heavyweight",
//       "81kg - Men's Half Middleweight",
//       "90kg - Men's Middleweight",
//       '100kg - Half Heavyweight',
//       '100kg+ - Heavyweight',
//       'Mixed Team',
//     ],
//     KAYAKING: [
//       'Canoe Slalom: C-1',
//       'Canoe Slalom: K-1',
//       'Canoe Slalom: KX-1',
//       'Canoe Sprint: C-1 200m',
//       'Canoe Sprint: C-1 1000m',
//       'Canoe Sprint: C-2 500m',
//       'Canoe Sprint: K-1 500m',
//       'Canoe Sprint: K-1 1000m',
//       'Canoe Sprint: K-2 500m',
//       'Canoe Sprint: K-4 500m',
//       'Rowing Sweep: Coxless Pair',
//       'Rowing Sweep: Coxless Four',
//       'Rowing Sweep: Coxless Eight',
//       'Rowing Sculling: Single Sculls',
//       'Rowing Sculling: Double Sculls',
//       'Rowing Sculling: Quadraple Sculls',
//       'Rowing Lightweight Sculling: Double Sculls',
//     ],
//     ROWING: [
//       'Canoe Slalom: C-1',
//       'Canoe Slalom: K-1',
//       'Canoe Slalom: KX-1',
//       'Canoe Sprint: C-1 200m',
//       'Canoe Sprint: C-1 1000m',
//       'Canoe Sprint: C-2 500m',
//       'Canoe Sprint: K-1 500m',
//       'Canoe Sprint: K-1 1000m',
//       'Canoe Sprint: K-2 500m',
//       'Canoe Sprint: K-4 500m',
//       'Rowing Sweep: Coxless Pair',
//       'Rowing Sweep: Coxless Four',
//       'Rowing Sweep: Coxless Eight',
//       'Rowing Sculling: Single Sculls',
//       'Rowing Sculling: Double Sculls',
//       'Rowing Sculling: Quadraple Sculls',
//       'Rowing Lightweight Sculling: Double Sculls',
//     ],
//     SAILING: [
//       "Men's Single-handed Dinghy - ILCA 7",
//       "Men's Dinghy - ILCA4",
//       "Women's Single-handed Dinghy - ILCA 6",
//       "Men's Skiff - 49er",
//       "Women's Skiff - 49erFX",
//       "Men's Windsurfer -IQFoil",
//       "Men's Windsurfer - RS:X",
//       "Women's Windsurfer - IQFoil",
//       "Men's Kiteboarding - The Formula Kite",
//       "Women's Kiteboarding -The Formula Kite",
//       'Mixed Double-handed Dinghy - 470',
//       'Mixed Foiling Catamaran - Nacra 17',
//     ],
//     SHOOTING: [
//       '10m Air Pistol',
//       '25m Standard Pistol',
//       '25m Center Fire Pistol',
//       '25m Rapid Fire Pistol',
//       '50m Pistol',
//       '10m Air Pistol Team',
//       '25m Standard Pistol Team',
//       '25m Center Fire Pistol Team',
//       '25m Rapid Fire Pistol Team',
//       '50m Pistol Team',
//       '10m Mixed Air Pistol Team',
//       '25m Rapid Fire Pistol Team',
//       '10m Air Rifle',
//       '50m Rifle',
//       '50m Rifle Prone',
//       'Team',
//       '50m Rifle 3 Position',
//       '300m Rifle',
//       '300m Rifle Prone',
//       '300m Rifle 3 Position',
//       '10m Air Rifle Team',
//       '50m Rifle Team',
//       '50m Rifle Prone Team',
//       '50m Rifle 3 Position Team',
//       '300m Rifle Team',
//       '300m Rifle Prone Team',
//       '300m Rifle 3 Position Team',
//       '10m Mixed Air Rifle Team',
//       'Shotgun Trap',
//       'Shotgun Double Trap',
//       'Shotgun Skeet',
//       'Shotgun Trap Team',
//       'Shotgun Double Trap Team',
//       'Shotgun Skeet Team',
//       'Shotgun Mixed Skeet Team',
//       'Target Sprint',
//       'Target Sprint Team',
//       '10m Running Target',
//       '10m Running Target Team',
//       '10m Running Target Mixed',
//       '10m Running Target Mixed Team',
//     ],
//     SWIMMING: [
//       '50m Freestyle',
//       '100m Freestyle',
//       '200m Freestyle',
//       '400m Freestyle',
//       '800m Freestyle',
//       '1500m Freestyle',
//       '100m Backstroke',
//       '200m Backstroke',
//       '100m Breaststroke',
//       '200m Breaststroke',
//       '100m Butterfly',
//       '200m Butterfly',
//       '200m Individual medley',
//       '400m Individual medley',
//       '4 x 100m Freestyle relay',
//       '4 x 200m Freestyle relay',
//       '4 x 100m Medlay relay',
//       '10km Open Water',
//     ],
//     TABLETENNIS: ['Singles', 'Doubles', 'Mixed Doubles', 'Team Event'],
//     TAEKWONDO: [
//       '54kg - Mens Finweight',
//       '58kg - Mens Flyweight',
//       '63kg - Mens Bantamweight',
//       '68kg - Mens Featherweight',
//       '74kg - Mens Lightweight',
//       '80kg - Mens Welterweight',
//       '87kg - Mens Middleweight',
//       '87kg+ - Mens Heavyweight',
//       '46kg - Womens Finweight',
//       '49kg - Womens Flyweight',
//       '53kg - Womens Bantamweight',
//       '57kg - Womens Featherwight',
//       '62kg - Womens Lightweight',
//       '67kg - Womens Welterweight',
//       "67kg+ - Women's Heavyweight",
//       '73kg - Womens Middleweight',
//       '73kg+ - Womens Heavyweight',
//     ],
//     TENNIS: ['Singles', 'Doubles', 'Mixed Doubles', 'Team Event'],
//     VOLLEYBALL: ['VOLLEYBALL'],
//     WEIGHTLIFTING: [
//       "61kg - Men's",
//       "67kg - Men's",
//       "73kg - Men's",
//       "81kg - Men's",
//       "96kg - Men's",
//       "109kg - Men's",
//       "109kg+ - Men's",
//       "49kg - Women's",
//       "55kg - Women's",
//       "59kg - Women's",
//       "64kg - Women's",
//       "76kg - Women's",
//       "87kg- Women's",
//       "87kg+ - Women's",
//     ],
//     WRESTLING: [
//       "57kg - Men's Freestyle",
//       "61kg - Men's Freestyle",
//       "65kg - Men's Freestyle",
//       "70kg - Men's Freestyle",
//       "74kg - Men's Freestyle",
//       "79kg - Men's Freestyle",
//       "86kg - Men's Freestyle",
//       "92kg - Men's Freestyle",
//       "97kg - Men's Freestyle",
//       "125kg - Men's Freestyle",
//       "5kg - Men's Greco-Roman",
//       "60kg - Men's Greco-Roman",
//       "63kg - Men's Greco-Roman",
//       "67kg - Men's Greco-Roman",
//       "72kg - Men's Greco-Roman",
//       "77kg - Men's Greco-Roman",
//       "82kg - Men's Greco-Roman",
//       "87kg - Men's Greco-Roman",
//       "97kg - Men's Greco-Roman",
//       "130kg - Men's Greco-Roman",
//       "50kg - Women's Freestyle",
//       "53kg - Women's Freestyle",
//       "55kg - Women's Freestyle",
//       "57kg - Women's Freestyle",
//       "59kg - Women's Freestyle",
//       "62kg - Women's Freestyle",
//       "65kg - Women's Freestyle",
//       "68kg - Women's Freestyle",
//       "72kg - Women's Freestyle",
//       "76kg - Women's Freestyle",
//     ],
//   },
//   playerCategory: [
//     'Senior',
//     'U-23',
//     'U-22',
//     'U-21',
//     'U-20',
//     'U-19',
//     'U-18',
//     'U-17',
//     'U-16',
//     'U-15',
//     'U-14',
//     'Para',
//   ],
//   playerGenderForEvent: [
//     "Individual Men's",
//     "Individual Women's",
//     "Team Men's",
//     "Team Women's",
//     'Mixed Team',
//   ],
//   scoreType: ['Points', 'Time'],
//   sports: [
//     'ARCHERY',
//     'ATHLETICS',
//     'BADMINTON',
//     'TABLETENNIS',
//     'TENNIS',
//     'BASKETBALL',
//     'BOXING',
//     'CANOEING',
//     'ROWING',
//     'KAYAKING',
//     'CYCLING',
//     'EQUESTRIAN',
//     'FENCING',
//     'FOOTBALL',
//     'HANDBALL',
//     'HOCKEY',
//     'VOLLEYBALL',
//     'GOLF',
//     'GYMNASTICS',
//     'JUDO',
//     'SHOOTING',
//     'SWIMMING',
//     'SAILING',
//     'TAEKWONDO',
//     'WEIGHTLIFTING',
//     'WRESTLING',
//   ],
// };
